In [10]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np
import seaborn as sns

In [29]:
data = pd.read_csv('cleanedNewTest.csv')

,props_pageProps_address_buildings_0_bathroomCondition,props_pageProps_address_buildings_0_buildingName,props_pageProps_address_buildings_0_externalWallMaterial,props_pageProps_address_buildings_0_heatingInstallation,props_pageProps_address_buildings_0_housingArea,props_pageProps_address_buildings_0_kitchenCondition,props_pageProps_address_buildings_0_numberOfFloors,props_pageProps_address_buildings_0_numberOfToilets,props_pageProps_address_buildings_0_roofingMaterial,props_pageProps_address_buildings_0_toiletCondition,...,props_pageProps_address_coordinates_lat,props_pageProps_address_coordinates_lon,props_pageProps_address_municipality_name,props_pageProps_address_events_0_at,props_pageProps_address_events_0_label,props_pageProps_dataLayer_virtualPagePath,props_pageProps_dataLayer_detailMetaData,lastPrice,sqm_price,years_from_today
0,Badeværelse i enheden,"(UDFASES) Række-, kæde- eller dobbelthus (lodr...",Mursten,Centralvarme med én fyringsenhed,101.0,Eget køkken med afløb,1,1,Betontagsten,Vandskyllende toilet i enheden,...,55.880930,12.345663,Allerød,2014-11-07 00:00:00+00:00,Fri handel,/adresse/williamsvej-18-3450-alleroed-02019645...,value:2350000|sqm:101|lastPrice:2545000|sqmPr:...,2545000.0,25198.019802,9
1,Badeværelse i enheden,Fritliggende enfamilieshus (parcelhus),Mursten,Centralvarme med én fyringsenhed,141.0,Eget køkken med afløb,1,1,Fibercement herunder asbest,Vandskyllende toilet i enheden,...,55.871070,12.352669,Allerød,2018-03-02 00:00:00+00:00,Fri handel,/adresse/aggebovej-11-3450-alleroed-02010099__...,value:2400000|sqm:141|lastPrice:3745000|sqmPr:...,3745000.0,26560.283688,5
2,Badeværelse i enheden,Fritliggende enfamilieshus (parcelhus),Mursten,Centralvarme med én fyringsenhed,139.0,Eget køkken med afløb,1,1,Tegl,Vandskyllende toilet i enheden,...,55.871640,12.352702,Allerød,2020-09-18 00:00:00+00:00,Fri handel,/adresse/aggebovej-17-3450-alleroed-02010099__...,value:3816000|sqm:139|lastPrice:2300000|sqmPr:...,2300000.0,16546.762590,3
3,Badeværelse i enheden,Fritliggende enfamilieshus (parcelhus),Mursten,Centralvarme med én fyringsenhed,168.0,Eget køkken med afløb,1,2,Tegl,Vandskyllende toilet i enheden,...,55.871815,12.353047,Allerød,2017-07-05 00:00:00+00:00,Fri handel,/adresse/aggebovej-21-3450-alleroed-02010099__...,value:2050000|sqm:168|lastPrice:4100000|sqmPr:...,4100000.0,24404.761905,6
4,Badeværelse i enheden,Fritliggende enfamilieshus (parcelhus),Mursten,Centralvarme med én fyringsenhed,120.0,Eget køkken med afløb,1,2,Tegl,Vandskyllende toilet i enheden,...,55.871490,12.353259,Allerød,2017-11-16 00:00:00+00:00,Fri handel,/adresse/aggebovej-22-3450-alleroed-02010099__...,value:3543000|sqm:120|lastPrice:2120393|sqmPr:...,2120393.0,17669.941667,6

In [25]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import folium

k = 9

# Selecting categorical and numerical columns
categorical_cols = data.select_dtypes(exclude=[np.number]).columns
numerical_cols = data.select_dtypes(include=[np.number]).columns

# One-Hot Encoding for categorical data
encoder = OneHotEncoder(sparse=False)
encoded_categorical_data = encoder.fit_transform(data[categorical_cols])

# Creating a DataFrame for encoded categorical data
new_columns = [f"{col}_{val}" for col, values in zip(categorical_cols, encoder.categories_) for val in values]
encoded_categorical_df = pd.DataFrame(encoded_categorical_data, columns=new_columns)

# Standardizing numerical data
scaler = StandardScaler()
scaled_numerical_data = scaler.fit_transform(data[numerical_cols])

# Creating a DataFrame for scaled numerical data
scaled_numerical_df = pd.DataFrame(scaled_numerical_data, columns=numerical_cols)

# Combining scaled numerical and encoded categorical data
combined_data = pd.concat([scaled_numerical_df, encoded_categorical_df], axis=1)

# Apply K-means clustering to the combined dataset
kmeans = KMeans(n_clusters=k, random_state=0)
clusters = kmeans.fit_predict(combined_data)
data['cluster'] = clusters

/Users/shakirmshaker/Library/Mobile Documents/com~apple~CloudDocs/Skole/DTU/ComputationalTools/Project/venv/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/Users/shakirmshaker/Library/Mobile Documents/com~apple~CloudDocs/Skole/DTU/ComputationalTools/Project/venv/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

In [28]:
combined_data.head()

,props_pageProps_address_buildings_0_housingArea,props_pageProps_address_buildings_0_numberOfFloors,props_pageProps_address_buildings_0_numberOfToilets,props_pageProps_address_buildings_0_yearBuilt,props_pageProps_address_coordinates_lat,props_pageProps_address_coordinates_lon,lastPrice,sqm_price,cluster,props_pageProps_address_buildings_0_bathroomCondition_Adgang til badeværelse,...,color_#5a00ff,color_#72ff00,color_#ad00ff,color_#c5ff00,color_#f800fd,color_#ff0065,color_#ff00b1,color_#ff4d00,color_#ff9a00,color_#ffec00
0,-0.106298,-0.63607,-0.577544,1.535500,1.064184,-0.323972,-0.250949,-0.221069,-1.160859,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.071342,-0.63607,-0.577544,0.287380,0.994817,-0.284413,-0.186566,-0.215534,-1.160859,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.062460,-0.63607,-0.577544,-0.087057,0.998827,-0.284226,-0.264094,-0.256224,-1.160859,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.191248,-0.63607,0.542124,-0.062094,1.000058,-0.282278,-0.167519,-0.224293,-1.160859,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.021919,-0.63607,0.542124,-0.136981,0.997772,-0.281081,-0.273730,-0.251660,-1.160859,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [26]:
data.groupby('cluster')[['lastPrice']].count()

         lastPrice
cluster
0             3838
1             3463
2             1076
3              681
4             1442
5              321
6             1187
7              914
8                7

In [27]:
# Assign a unique color to each cluster
palette = sns.color_palette("hsv", k).as_hex()
data['color'] = data['cluster'].apply(lambda x: palette[x])

# Create a new map for the combined dataset
map_center_lat, map_center_lon = data['props_pageProps_address_coordinates_lat'].mean(), data['props_pageProps_address_coordinates_lon'].mean()
combined_map = folium.Map(location=[map_center_lat, map_center_lon], zoom_start=7)

# Add the properties to the combined map
for _, row in data.iterrows():
    folium.CircleMarker(
        location=[row['props_pageProps_address_coordinates_lat'], row['props_pageProps_address_coordinates_lon']],
        radius=5,
        color=row['color'],
        fill=True,
        fill_color=row['color']
    ).add_to(combined_map)

# Save the new map
combined_map_file_path = 'denmark_property_combined_map.html'
combined_map.save(combined_map_file_path)
combined_map_file_path

'denmark_property_combined_map.html'